name: on-pull-request
on: [workflow_dispatch,pull_request]
jobs:
  build-n-test:
    env:
      POETRY_CACHE_FOLDER: '/home/runner/.cache/pypoetry/virtualenvs'
      JUNIT_REPORT_PATH: pytest-junit-report
    runs-on: ubuntu-20.04    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.POETRY_CACHE_FOLDER }}
          key:  poetry-pr-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - run: poetry install

      - id: check
        run: poetry run poe check

      - id: collect-pytest-reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: reports/junit
      - id: collect-pytest-cov-reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-cov-report
          path: reports/cov
      - name: Display JUnit results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{env.JUNIT_REPORT_PATH}}/*.xml
